### ISSUE TITLE
Downgrade Gradle to 6.0.1

### ISSUE THREAD

**Issue by oskarjerzyk** [Knotx/knotx-gradle-plugins#17]
Because of build failures on Windows when using Gradle version higher than or equal to 6.1 we have to downgrade Gradle to version 6.0.1 - this is the latest fully working version. This issue is related only to knotx-gradle-plugins repository, others could be upgraded to the newest version

**Comment by tomaszmichalak** [comment]
It looks that it works with Gradle 6.3.
