### ISSUE TITLE
Codegen plugin does not generate adocs

### ISSUE THREAD

**Issue by malaskowski** [Knotx/knotx-gradle-plugins#3]
### Version
`0.1.0`

### Description
It looks that generating ascidocs is no longer working when applying `id("io.knotx.codegen")` plugin.

Converters are generated but the code responsible for creating docs:
```
    options.compilerArgs = listOf(
            "-processor", "io.vertx.codegen.CodeGenProcessor",
            "-Acodegen.output=${project.projectDir}/docs"
    )
```
is not working.

**Comment by tMaxx** [comment]
The issue here is the order of operations. If `unit-test` plugin is declared in build file after `codegen`, then adocs don't generate. Tested in `knotx-template-engine`, it's what I had at hand.

I'll try to fix it, should be fairly simple :)
